language: python

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Linux-64bit.tar.gz
  - tar -xf hugo_0.75.1_Linux-64bit.tar.gz

script:
  - ./hugo

deploy:

  - provider: netlify
    dir: ./public/
    site: $NETLIFY_SITE
    auth: $NETLIFY_AUTH
    edge: true
    prod: false
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = feature/make-travis-publish-feature
